### PR TITLE
update Tango skin, adapt to Library redesign

### PR DESCRIPTION
**Pull request by ronso0**
I also removed the duplicate feature title ("Tracks" etc.) from feature pane, so it's displayed above tracks table only.

Check it out!

### CODE REVIEW

**Comment by ronso0** [comment]
I'm not done, yet, as I will also style the buttons in some Library features.

**Comment by ronso0** [comment]
This can be merged if you like it.

**Comment by ronso0** [comment]
@gramanas Did you find time to test this yet?

**Comment by gramanas** [comment]
@ronso0 I am really sorry, I did not get any notifications for this at all. I'll test it ASAP and probably merge it by the looks of it :) thanks!

**Comment by gramanas** [comment]
I can't see the library at all!

2018-02-08-160650_1466x977_scrot

**Comment by ronso0** [comment]
I'll also merge the fixes from [mixxxdj:#1521](https://github.com/mixxxdj/mixxx/pull/1512)

**Comment by ronso0** [comment]
> I can't see the library at all!

I'll have a look.

**Comment by ronso0** [comment]
Are you sure you're testing this with lib-redesign compiled?
Because, it's strange that not even the Breadcrumbs show up next to search box..

Should look like this:
tango_2018-02-08_check

**Comment by gramanas** [comment]
Yeah, you are right. I am compiling with the redesign as I type this. 

I though after doing this `git fetch origin pull/ID/head:BRANCHNAME` I would have the redesign with your changes in it, but apparently I don't! I merged it locally, I think it should work.

**Comment by gramanas** [comment]
Yup, it looks just fine. My only issue is that the library search bar seems a bit weird up there. I want to be able to resize it. 

How would you like it, if it was more like deree's (it's locked with the size of the main library pane).

Also the text of the sidebar icons is too dark to be able to clearly read it in this background!

2018-02-08-180800_1843x1005_scrot

**Comment by ronso0** [comment]
Okay, now the feature buttons have an explicit font color set.

The issue I have with the search box: it can't be sized dynamically, it just occupies the full width and the buttons to clear, save or recall the search queries are at the far right. This is annoying, already on my medium-sized screen (1366x768).
To make full use of the Breadcrumbs, IMO they should have more space available than we above the feature pane. There they are cropped/elided as soon as you choose "Artsist ft. Anyone > Great Album 2012" (consider smaller screens and narrow feature pane).
On the other hand it feels they waste vertical space if we grant them a full row above the search box.

I'll play around with the layout next weekend...

**Comment by gramanas** [comment]
Ok, play around with it and let me know if you have any idea that works. We could ask on Zulip for suggestions.

Another thing that should change is the colour of the letters inside the left pane's scrollbar, it's hard to read them. And if it is possible, you could also change the opacity of the actual slider block so you can see the letters behind it.

**Comment by gramanas** [comment]
Ok, play around with it and let me know if you have any idea that works. We could ask on Zulip for suggestions.

Another thing that should change is the colour of the letters inside the left pane's scrollbar, it's hard to read them. And if it is possible, you could also change the opacity of the actual slider block so you can see the letters behind it.

**Comment by ronso0** [comment]
Also it's interesting that the Feature pane's border should be drawn left to the scrollbar, but on your screen it's drawn around the Feature pan incl. scrollbar
On which OS are you?

**Comment by gramanas** [comment]
>    On which OS are you?

Arch Linux

**Comment by ronso0** [comment]
> the colour of the letters inside the left pane's scrollbar

fixed.

Also I think I found a soluton for the BreadCrumb issue. It now fits above feature pane. If you drag the vertical splitter, and the pane gets too narrow (or even collapses), BreadCrumbs show up left to search box.
What do you think?

**Comment by gramanas** [comment]
I'll test it as soon as I get home!

**Comment by gramanas** [comment]
Ok, it seems nice. Any further adjustments should occur after my PR is merged in the main repo.
Thanks for helping!

**Pull request merged**
